name: ukrtransnaftaadmin
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.2
  cloud_firestore: ^4.13.6
  fluent_ui: ^4.8.2
  provider: ^6.1.1
  shared_preferences: ^2.0.13
  flutter_map: ^3.1.0
  latlong2: ^0.8.1
  fluentui_system_icons: ^1.1.270
  flutter_launcher_icons: ^0.14.2

flutter_launcher_icons:
  image_path: "assets/logo.png"
  windows:
    generate: true
    icon_size: 256

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  msix: ^3.16.8

flutter:
  uses-material-design: true

msix_config:
  display_name: Адміністратор компаньйону УТФ
  publisher_display_name: Адміністратор компаньйону УТФ
  identity_name: com.ukrtransnafta.admin
  msix_version: 1.0.0.0
  logo_path: assets\logo.png
  capabilities: internetClient, location, microphone, webcam